// Generated by https://quicktype.io

export interface BadRequestReferenteResponse {
    statusCode:             string;
    headers:                Headers;
    detailMessageCode:      string;
    detailMessageArguments: null;
    titleMessageCode:       string;
    body:                   Body;
}

export interface Body {
    type:            string;
    title:           string;
    status:          number;
    detail:          string;
    "Fields errors": FieldsError[];
}

export interface FieldsError {
    object:        string;
    message:       string;
    field:         string;
    rejectedValue: string;
}

export interface Headers {
}
