
// Generated by https://quicktype.io

export interface Alumno {
    id:              string;
    nombre:          string;
    apellido:        string;
    fechaNacimiento: string;
    telefono:        string;
    email:           string;
}
